services:
  postgres:
    image: postgres:16
    container_name: redcybers-postgres
    environment:
      POSTGRES_DB: redcybers
      POSTGRES_USER: redcybers
      POSTGRES_PASSWORD: redcybers
    ports:
      - "5432:5432"
    volumes:
      - redcybers_pg:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: redcybers-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - redcybers_es:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: redcybers-logstash
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: redcybers-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./elk/kibana/redcybers-logo.png:/usr/share/kibana/config/branding/redcybers-logo.png
      - ./elk/kibana/redcybers-favicon.png:/usr/share/kibana/config/branding/redcybers-favicon.png
volumes:
  redcybers_pg:
  redcybers_es:
